
import os

from web3 import Web3
from dotenv import load_dotenv


# =========================================
# BLOCKCHAIN CONNECTION
# =========================================

def connect_blockchain():

    load_dotenv()

    rpc_url = os.getenv("RPC_URL")

    if not rpc_url:
        raise RuntimeError(
            "RPC_URL not found in .env"
        )

    web3 = Web3(
        Web3.HTTPProvider(rpc_url)
    )

    if not web3.is_connected():
        raise RuntimeError(
            "Could not connect to blockchain"
        )

    print("Blockchain connected!")
    print(
        "Chain ID:",
        web3.eth.chain_id
    )

    return web3


# =========================================
# VERIFY FINGERPRINT
# =========================================

def verify_fingerprint(
    transaction_hash,
    original_fingerprint
):

    web3 = connect_blockchain()

    # -----------------------------------------
    # Validate inputs
    # -----------------------------------------

    if not transaction_hash:
        raise ValueError(
            "Transaction hash cannot be empty."
        )

    if not original_fingerprint:
        raise ValueError(
            "Original fingerprint cannot be empty."
        )

    # -----------------------------------------
    # Get transaction
    # -----------------------------------------

    print("\nReading blockchain transaction...")

    tx = web3.eth.get_transaction(
        transaction_hash
    )

    # -----------------------------------------
    # Extract stored fingerprint
    # -----------------------------------------

    stored_fingerprint = web3.to_text(
        tx["input"]
    ).rstrip("\x00")

    # -----------------------------------------
    # Display verification data
    # -----------------------------------------

    print("\n================================")
    print("BLOCKCHAIN VERIFICATION")
    print("================================")

    print(
        "Transaction :",
        transaction_hash
    )

    print(
        "Block       :",
        tx["blockNumber"]
    )

    print(
        "Stored hash :",
        stored_fingerprint
    )

    print(
        "Original hash:",
        original_fingerprint
    )

    # -----------------------------------------
    # Compare fingerprints
    # -----------------------------------------

    verified = (
        stored_fingerprint
        == original_fingerprint
    )

    if verified:

        print("\n✅ VERIFICATION SUCCESSFUL")

        print(
            "Fingerprint matches "
            "the blockchain record."
        )

    else:

        print("\n❌ VERIFICATION FAILED")

        print(
            "Fingerprint does not match "
            "the blockchain record."
        )

    print("================================")

    # -----------------------------------------
    # Return verification result
    # -----------------------------------------

    return verified


# =========================================
# DIRECT TEST
# =========================================

if __name__ == "__main__":

    # Transaction generated by write_record.py
    transaction_hash = (
        "e6c677151139db70d10ed577c75b29fc9b8ee9a318e627867c74210e204c48d6"
    )

    # Fingerprint written to blockchain
    original_fingerprint = (
        "6691dc75735f55d506261f7c80ebc8e004bdfb7c1628ccd3152ae99f02add1c8"
    )

    verified = verify_fingerprint(
        transaction_hash,
        original_fingerprint
    )

    print("\n================================")
    print("VERIFICATION RESULT")
    print("================================")

    print(
        "Verified:",
        verified
    )

    print("================================")
